get_sampling_effort:
  url: https://github.com/Mosquito-Alert/sampling_effort_data/raw/main/sampling_effort_daily_cellres_025.csv.gz

h3_res: 6

# Get from
# NOTE: do not use -> from rasterio.warp import transform_bounds
# import rasterio
# from pyproj import Transformer
# src = rasterio.open('./U2018_CLC2018_V2020_20u1.tif')
# transformer = Transformer.from_crs(src.crs, "EPSG:4326", always_xy=True)
# bounds = src.bounds
# min_lon, min_lat = transformer.transform(bounds.left, bounds.bottom)
# max_lon, max_lat = transformer.transform(bounds.right, bounds.top)
# transform_bounds(src.crs, "EPSG:4326", *src.bounds)
era5:
  min_lon: -32.43
  min_lat: 26.40
  max_lon: 72.91
  max_lat: 51.0