get_sampling_effort:
  url: https://github.com/Mosquito-Alert/sampling_effort_data/raw/main/sampling_effort_daily_cellres_025.csv.gz

h3_res: 6

# Get from
# import rasterio
# from rasterio.warp import transform_bounds
# src = rasterio.open('./U2018_CLC2018_V2020_20u1.tif')
# transform_bounds(src.crs, "EPSG:4326", *src.bounds)
era5:
  min_lon: -56.51
  min_lat: 24.27
  max_lon: 72.91
  max_lat: 72.64