__use_yte__: true
executor: slurm
slurm-no-account: true
slurm-logdir: "/home/$USER/.snakemake/slurm_logs"
default-resources:
  # slurm_account: default   # TODO: --slurm-no-account
  slurm_partition: ceab
  mem_mb: attempt * 1500
  runtime: attempt * 10
  tmpdir: /lscratch/tmp
  # slurm_extra: "--mail-type=BEGIN,END,FAIL --mail-user=usuario@correo"
jobs: 30
latency-wait: 60
retries: 1

default-storage-provider: fs
remote-job-local-storage-prefix: /lscratch/$USER/\$JOBID
local-storage-prefix: /home/$USER
shared-fs-usage:
  - persistence
  - software-deployment
  - sources
  - source-cache


# Also do the: --slurm-requeue
